name: github-action

env:
  apiKey: "7557df3b6bdcde7786e67b71"
  apiSecret: "c7dbead577a1293683f08918981ec683af3139212f6be7520aafc65da35b344055000459"
  testID: "14135112"
  continuePipeline: "false"
  showTailLog: "false"
  ACTIONS_STEP_DEBUG: true

on:
  push:

jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run Blazemeter test
        uses: BlazeRunner-BZR/Github-Action@v8.7
        id: run-test
        with:
          apiKey: ${{ env.apiKey }}
          apiSecret: ${{ env.apiSecret }}
          testID: ${{ env.testID }}
          continuePipeline: ${{ env.continuePipeline }}
          showTailLog: ${{ env.showTailLog }}
